; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1, esp32-s3-devkitc-1-ota

[env:esp32-s3-devkitc-1]
platform = https://github.com/platformio/platform-espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = partitions/badge_factory_ota.csv
build_flags = 
	-D NSEC_BADGE_YEAR=2026
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D HAS_CONFERENCE=1
lib_deps = 
	core
	conference
	knolleary/PubSubClient@^2.8
monitor_speed = 115200
monitor_filters = 
	default
	time
monitor_rts = 0
monitor_dtr = 0
board_build.filesystem = spiffs

[env:esp32-s3-devkitc-1-ota]
extends = env:esp32-s3-devkitc-1
board_upload.offset_address = 0x150000
build_flags = 
	-D NSEC_BADGE_YEAR=2026
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D HAS_CHALLENGES=1
lib_deps = 
	core
	challenges
	knolleary/PubSubClient@^2.8
lib_ldf_mode = deep+
