M48
; DRILL file {KiCad 9.0.7} date 2026-04-20T21:55:25-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-20T21:55:25-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X9.4082Y-2.4537
X9.7082Y-2.4537
T2
X9.4863Y-2.212
X9.5863Y-2.212
M30
