#pragma once

// Convenience include for core subsystems.

#include "tasks/cli.h"
#include "tasks/cli_queue.h"
#include "tasks/cli_task.h"
#include "tasks/controller.h"
#include "tasks/controller_task.h"
#include "tasks/heartbeat.h"
#include "tasks/led.h"
#include "tasks/led_task.h"
#include "tasks/button_task.h"
#include "tasks/nfc.h"
#include "tasks/nfc_task.h"
#include "tasks/dock_task.h"
#include "tasks/light_task.h"
#include "hardware/buttons.h"
#include "hardware/hwid.h"
#include "hardware/nfc.h"
#include "hardware/dock.h"
#include "hardware/light_sensor.h"
#include "hardware/rgb_led.h"
#include "hardware/status_led.h"
#include "storage/nvs_social.h"
#include "system/ota_manager.h"
