M48
; DRILL file {KiCad 9.0.7} date 2026-03-09T17:58:37-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-09T17:58:37-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X7.0348Y-4.4287
X7.1455Y-4.6284
T2
X6.8441Y-5.1625
X6.9276Y-5.079
M30
